[mainConfig]
appName = "HavenCamp"
host = "0.0.0.0"
port = 8000

[mysqlConfig]
host = "mysql"
port = 3306
user = "root"
password = "123456"
databaseName = "haven_camp_server"

[redisConfig]
host = "redis"
port = 6379
password = ""
db = 0

[authCodeConfig]
accessKeyID = "your accessKeyID in alibaba cloud"
accessKeySecret = "your accessKeySecret in alibaba cloud"
signName = "阿里云短信测试"
templateCode = "SMS_154950909"

[logConfig]
logPath = "./logs"

[kafkaConfig]
messageMode = "kafka"# 消息模式 channel or kafka
hostPort = "kafka:9092" # Docker环境中的Kafka服务
loginTopic = "login"
chatTopic = "chat_message"
logoutTopic = "logout"
partition = 0 # kafka partition
timeout = 1 # 单位秒

[staticSrcConfig]
staticAvatarPath = "./static/avatars"
staticFilePath = "./static/files" 